title: Alex Britz - Portfolio
logo: /assets/Alex-Britz_Profil.jpg
theme: jekyll-theme-minimal
description: Trainer, Coach, Facilitator and Lecturer with expertise in Python, data Analysis and visualization, AI applications for science and scademia, scientific writing and presentation, conflict resolution, ethics of science and academia
